version: '3.4'

services:
  apidb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Qwert.123
      - ACCEPT_EULA=Y
    volumes:
      - mssqlserver_volume:/var/opt/mssql
    ports:
      - "1433:1433"

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

volumes:
  mssqlserver_volume: