version: '3.4'

services:
  apidb:
    container_name: apidb
    restart: always
    ports:
      - "1433:1433"

  webapi:
    container_name: webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:db=Data Source=apidb;Initial Catalog=df;user id=sa;password=yourStrong(!)Password;"
    depends_on:
      - apidb
    ports:
      - "8000:80"
