version: '3.4'

services:
  apidb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
