version: '3.4'

services:
  apidb:
    container_name: apidb
    restart: always

  webapi:
    container_name: webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:db=\"Data Source=apidb;Initial Catalog=df;user id=sa;password=Qwert.123;\""
    depends_on:
      - apidb
    ports:
      - "8000:80"
